--creating our database and inserting values
--create
Create Table antrenor(
    antrenorID number generated by default as identity,
    nume varchar2(35),
    prenume varchar2(35),
    varsta number,
    club varchar2(35),
    PRIMARY KEY(antrenorID)
)


Create Table echipament(
    echipamentID number generated by default as identity,
    tip_echipament varchar2(35),
    model_echipament varchar2(35),
    PRIMARY KEY(echipamentID)
)

Create Table bar(
    barID number generated by default as identity,
    nume_bar varchar2(35),
    nume_barman varchar2(35),
    telefon varchar2(20),
    email_bar varchar2(35),
    PRIMARY KEY(barID)
)

Create Table spectatori(
    spectatorID number generated by default as identity,
    nume varchar2(35),
    prenume varchar2(35),
    cnp varchar2(15),
    email varchar2(35),
    PRIMARY KEY(spectatorID)
)

Create Table concurs(
    concursID number generated by default as identity,
    nume_concurs varchar2(35),
    tara varchar2(35),
    localitate varchar2(35),
    data_concurs date,
    pret_bilet number,
    PRIMARY KEY(concursID)
)

Create Table dj(
    djID number generated by default as identity,
    nume varchar2(35),
    prenume varchar2(35),
    data_nasterii date,
    tarif float,
    data_contract date,
    PRIMARY KEY(djID)
)

Create Table sponsor(
    sponsorID number generated by default as identity,
    nume_sponsor varchar2(35),
    email_sponsor varchar2(35),
    PRIMARY KEY(sponsorID),
    echipamentID number constraint echipamentFK references echipament

)

Create Table scena(
    scenaID number generated by default as identity,
    nume_scena varchar2(35),
    PRIMARY KEY(scenaID),
    concursID number constraint concursFK references concurs,
    djID number constraint djFK references dj
)

Create Table copii(
    copilID number generated by default as identity,
    nume varchar2(35),
    prenume varchar2(35),
    numeDans varchar2(35),
    numeMelodie varchar2(35),
    PRIMARY KEY(copilID),
    antrenorID number constraint antrenorFK references antrenor
)

Create Table solo(
    vechimeDans number,
    copilID number constraint copil_ID references copii,
    PRIMARY KEY(copilID)
)

Create Table team(
    numar_membri number,
    data_infiintare date,
    copilID number constraint copil_ID1 references copii,
    PRIMARY KEY(copilID)
)

Create Table abonament(
    concursID number constraint concurs_ID references concurs,
    pret_abonament float, 
    valabilitate date,
    spectatorID number constraint spectator_ID references spectatori,
    PRIMARY KEY(concursID, spectatorID)
)

Create Table program(
    programID number generated by default as identity,
    program_start date,
    program_final date,
    PRIMARY KEY(programID),
    scenaID number constraint scena_FK references scena,
    djID number constraint dj_FK references dj
)

Create Table comercializare(
    comercializareID number generated by default as identity,
    valabilitate_contract date,
    PRIMARY KEY(comercializareID),
    concursID number constraint concurs_FK references concurs,
    barID number constraint bar_FK references bar
)

Create Table sponsorizare(
    sponsorizareID number generated by default as identity,
    valabilitate_sponsorizare date,
    PRIMARY KEY(sponsorizareID),
    concursID number constraint concursFK1 references concurs,
    sponsorID number constraint sponsor_FK1 references sponsor
)

Create Table participare(
    participareID number generated by default as identity,
    ora_incepere timestamp,
    PRIMARY KEY(participareID),
    concursID number constraint concursFK2 references concurs,
    copilID number constraint copilFK2 references copii
)

--insert

INSERT INTO antrenor(antrenorID, nume, prenume, varsta, club)
values (secventa.NEXTVAL, 'Popa', 'Antonia', '25', 'Steaua');

INSERT INTO antrenor(antrenorID, nume, prenume, varsta, club)
values (secventa.NEXTVAL, 'Miron', 'Mircea', '30', 'WildCats');

INSERT INTO antrenor(antrenorID, nume, prenume, varsta, club)
values (secventa.NEXTVAL, 'Ionescu', 'Mihaela', '20', 'Steaua');

INSERT INTO antrenor(antrenorID, nume, prenume, varsta, club)
values (secventa.NEXTVAL, 'Andrei', 'Corina', '36', 'Brasov');

INSERT INTO antrenor(antrenorID, nume, prenume, varsta, club)
values (secventa.NEXTVAL, 'Dan', 'Vlad', '28', 'WildCats');

-- bar
INSERT INTO bar(barID, nume_bar, nume_barman, telefon, email_bar)
values(secventa_bar.NEXTVAL, 'Shake', 'Andrei', '0751276547', 'shake@yahoo.com');

INSERT INTO bar(barID, nume_bar, nume_barman, telefon, email_bar)
values(secventa_bar.NEXTVAL, 'Euphoria', 'Maria', '0751476545', 'euphoria@gmail.com');

INSERT INTO bar(barID, nume_bar, nume_barman, telefon, email_bar)
values(secventa_bar.NEXTVAL, 'Fire', 'Mircea', '0747865435', 'fire@yahoo.com');

INSERT INTO bar(barID, nume_bar, nume_barman, telefon, email_bar)
values(secventa_bar.NEXTVAL, '13', 'Dana', '0776856128', 'treisprezece@yahoo.com');

INSERT INTO bar(barID, nume_bar, nume_barman, telefon, email_bar)
values(secventa_bar.NEXTVAL, 'Starbucks', 'Darius', '0726574653', 'starbucks@gmail.com');

--dj
INSERT INTO dj(djID, nume, prenume, data_nasterii, tarif, data_contract)
values(secventa_dj.nextval, 'Anghel', 'Mihai', '04/06/1997', '1000', '02/05/2022');

INSERT INTO dj(djID, nume, prenume, data_nasterii, tarif, data_contract)
values(secventa_dj.nextval, 'Dan', 'Andrei', '02/07/1995', '1200', '07/05/2022');

INSERT INTO dj(djID, nume, prenume, data_nasterii, tarif, data_contract)
values(secventa_dj.nextval, 'Oprea', 'Mirabela', '01/08/1997', '1150', '03/05/2022');

INSERT INTO dj(djID, nume, prenume, data_nasterii, tarif, data_contract)
values(secventa_dj.nextval, 'Darian', 'George', '03/07/1998', '1100', '01/05/2022');

INSERT INTO dj(djID, nume, prenume, data_nasterii, tarif, data_contract)
values(secventa_dj.nextval, 'Popa', 'Dragos', '10/01/1992', '1300', '06/05/2022');

--echipament
INSERT INTO echipament(echipamentID, tip_echipament, model_echipament)
values (secventa_echipament.nextval, 'Costum', 'Bershka');

INSERT INTO echipament(echipamentID, tip_echipament, model_echipament)
values (secventa_echipament.nextval, 'Rochie', 'Cropp');

INSERT INTO echipament(echipamentID, tip_echipament, model_echipament)
values (secventa_echipament.nextval, 'Fusta', 'Bershka');

INSERT INTO echipament(echipamentID, tip_echipament, model_echipament)
values (secventa_echipament.nextval, 'Tricou', 'Orsay');

INSERT INTO echipament(echipamentID, tip_echipament, model_echipament)
values (secventa_echipament.nextval, 'Fusta', 'H&M');

--concurs
INSERT INTO concurs(concursID, nume_concurs, tara, localitate, data_concurs, pret_bilet)
values(secventa_concurs.nextval, 'Floricica', 'Romania', 'Bucuresti', '04/08/2022', 60);

INSERT INTO concurs(concursID, nume_concurs, tara, localitate, data_concurs, pret_bilet)
values(secventa_concurs.nextval, 'Star', 'Romania', 'Craiova', '04/09/2022', 20);

INSERT INTO concurs(concursID, nume_concurs, tara, localitate, data_concurs, pret_bilet)
values(secventa_concurs.nextval, 'Evolution', 'Romania', 'Suceava', '03/01/2022', 50);

INSERT INTO concurs(concursID, nume_concurs, tara, localitate, data_concurs, pret_bilet)
values(secventa_concurs.nextval, 'Simba', 'Romania', 'Brasov', '02/10/2022', 30);

INSERT INTO concurs(concursID, nume_concurs, tara, localitate, data_concurs, pret_bilet)
values(secventa_concurs.nextval, 'Dance Open', 'Romania', 'Bucuresti', '01/09/2022', 80);

--scena
INSERT INTO scena(scenaID, nume_scena, concursID, djID)
values (secventa_scena.nextval, 'Scena Principala', '1', '3');

INSERT INTO scena(scenaID, nume_scena, concursID, djID)
values (secventa_scena.nextval, 'Scena Dramei', '4', '1');

INSERT INTO scena(scenaID, nume_scena, concursID, djID)
values (secventa_scena.nextval, 'Scena Florilor', '3', '2');

INSERT INTO scena(scenaID, nume_scena, concursID, djID)
values (secventa_scena.nextval, 'Scena Fericirii', '1', '3');

INSERT INTO scena(scenaID, nume_scena, concursID, djID)
values (secventa_scena.nextval, 'Scena Muzicala', '5', '5');

--sponsor

INSERT INTO sponsor(sponsorID, nume_sponsor, email_sponsor, echipamentID)
values(secventa_sponsor.nextval, 'Mega Image', 'mega@yahoo.com', '3');

INSERT INTO sponsor(sponsorID, nume_sponsor, email_sponsor, echipamentID)
values(secventa_sponsor.nextval, 'Oracle', 'oracle@gmail.com', '2');

INSERT INTO sponsor(sponsorID, nume_sponsor, email_sponsor, echipamentID)
values(secventa_sponsor.nextval, 'Pepsi', 'pepsi@yahoo.com', '1');

INSERT INTO sponsor(sponsorID, nume_sponsor, email_sponsor, echipamentID)
values(secventa_sponsor.nextval, 'Pepco', 'pepco@yahoo.com', '5');

INSERT INTO sponsor(sponsorID, nume_sponsor, email_sponsor, echipamentID)
values(secventa_sponsor.nextval, 'LC Waikiki', 'waikiki@gmail.com', '4');

--spectatori

INSERT INTO spectatori(spectatorID, nume, prenume, cnp, email)
values(secventa_spectator.nextval, 'Cimpu','Denisa','6010804080016','denisa_cimpu2001@yahoo.com');

INSERT INTO spectatori(spectatorID, nume, prenume, cnp, email)
values(secventa_spectator.nextval, 'Popescu','Antonio','5040604070023','popescu_antonio@yahoo.com');

INSERT INTO spectatori(spectatorID, nume, prenume, cnp, email)
values(secventa_spectator.nextval, 'Dan','Adrian','5990703090844','adrian_adi@gmail.com');

INSERT INTO spectatori(spectatorID, nume, prenume, cnp, email)
values(secventa_spectator.nextval, 'Ionescu','Ariana','6980405096687','ariana_ione@yahoo.com');

INSERT INTO spectatori(spectatorID, nume, prenume, cnp, email)
values(secventa_spectator.nextval, 'Stanciu','Mihai','5030908070098','stanciumihaita98@yahoo.com');

--copii

INSERT INTO copii(copilID, nume, prenume, numeDans, numeMelodie, antrenorID)
values(secventa_copii.nextval, 'Andrei', 'Mihaita', 'Micul Dansator', 'Danza Kuduro', '5');

INSERT INTO copii(copilID, nume, prenume, numeDans, numeMelodie, antrenorID)
values(secventa_copii.nextval, 'Ioan', 'Daria', 'Gargarita', 'In padurea cu alune', '3');

INSERT INTO copii(copilID, nume, prenume, numeDans, numeMelodie, antrenorID)
values(secventa_copii.nextval, 'Anghelina', 'Ingrid', 'Micul Dansator', 'Danza Kuduro', '5');

INSERT INTO copii(copilID, nume, prenume, numeDans, numeMelodie, antrenorID)
values(secventa_copii.nextval, 'Oancea', 'Ionut', 'Sofisticat', 'Sus pe toc', '1');

INSERT INTO copii(copilID, nume, prenume, numeDans, numeMelodie, antrenorID)
values(secventa_copii.nextval, 'Bobina', 'Oana', 'Little Angel', 'Twinkle Twinkle Little Star', '2');

--solo

INSERT INTO solo(copilID, vechimeDans)
values(secventa_solo.nextval, '2');

INSERT INTO solo(copilID, vechimeDans)
values(secventa_solo.nextval, '10');

INSERT INTO solo(copilID, vechimeDans)
values(secventa_solo.nextval, '5');

INSERT INTO solo(copilID, vechimeDans)
values(secventa_solo.nextval, '4');

INSERT INTO solo(copilID, vechimeDans)
values(secventa_solo.nextval, '12');

--team

INSERT INTO team(copilID, numar_membri, data_infiintare)
values(secventa_team.nextval, '2', '03/08/2021');

INSERT INTO team(copilID, numar_membri, data_infiintare)
values(secventa_team.nextval, '3', '10/04/2020');

INSERT INTO team(copilID, numar_membri, data_infiintare)
values(secventa_team.nextval, '2', '03/18/2019');

INSERT INTO team(copilID, numar_membri, data_infiintare)
values(secventa_team.nextval, '4', '07/28/2021');

INSERT INTO team(copilID, numar_membri, data_infiintare)
values(secventa_team.nextval, '3', '06/19/2017');

--abonament

INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('1', '2', '100', '04/09/2023');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('3', '5', '150', '10/09/2023');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('2', '1', '100', '04/08/2023');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('1', '3', '200', '03/09/2024');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('5', '5', '300', '04/09/2025');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('2', '5', '175', '12/12/2023');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('1', '1', '185', '02/12/2023');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('5', '5', '400', '12/12/2026');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('4', '5', '185', '01/01/2024');
INSERT INTO abonament(concursID, spectatorID, pret_abonament, valabilitate)
values('3', '3', '195', '03/03/2024');

--program

INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '04/08/2022', '04/08/2022','1','2');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '03/01/2022', '03/01/2022','3','5');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '05/05/2023', '05/06/2023','1','4');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '07/03/2024', '07/05/2022','5','4');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '10/11/2022', '10/11/2022','3','2');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '09/07/2024', '09/08/2022','4','4');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '01/02/2023', '01/02/2023','1','5');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '04/10/2024', '04/10/2024','2','2');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '10/12/2022', '12/12/2022','3','1');
INSERT INTO program(programID, program_start, program_final, scenaID, djID)
values(secventa_program.nextval, '02/25/2023', '02/26/2023','4','3');

--comercializare

INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '12/28/2022', '2', '5');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '05/29/2023', '1', '4');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '09/02/2023', '1', '5');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '07/01/2024', '5', '5');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '11/17/2023', '4', '4');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '10/19/2024', '3', '1');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '12/31/2022', '4', '2');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '01/01/2025', '2', '1');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '05/01/2023', '3', '2');
INSERT INTO comercializare(comercializareID, valabilitate_contract, concursID, barID)
values(secventa_comercializare.nextval, '03/29/2024', '4', '3');

--sponsorizare

INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '10/29/2022', '2', '5');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '07/30/2023', '1', '1');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '01/01/2024', '3', '4');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '12/31/2025', '3', '1');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '11/30/2022', '2', '3');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '01/03/2024', '4', '5');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '08/18/2023', '3', '2');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '04/20/2024', '5', '2');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '12/12/2025', '5', '5');
INSERT INTO sponsorizare(sponsorizareID, valabilitate_sponsorizare, concursID, sponsorID)
values(secventa_sponsorizare.nextval, '10/30/2022', '2', '1');

--participare

INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '09/07/2022', '2', '3');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '02/19/2023', '1', '5');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '12/19/2022', '5', '3');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '03/08/2023', '1', '1');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '02/20/2023', '2', '5');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '09/07/2022', '2', '4');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '04/10/2022', '4', '3');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '05/19/2024', '3', '1');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '10/10/2023', '2', '5');
INSERT INTO participare(participareID, data_participare, concursID, copilID)
values(secventa_participare.nextval, '12/12/2022', '5', '5');
